// testApi.js
import express from 'express';
import bodyParser from 'body-parser';
//canım sevgilim canım sevgilim
//ben sevgilimi cok seviyorum
//kalp kalp kalp
//ask
const app = express();
app.use(bodyParser.json());

// This endpoint mimics SMS API. It logs the incoming data and responds with a fake jobid.
app.post('/sms/send/rest/v1', (req, res) => {
  console.log('Test API received request:', req.body);
  // Generate a random jobid (in a real scenario this would be generated by the SMS provider)
  const jobid = Math.floor(Math.random() * 10000000000);
  res.json({
    code: "00",                // "00" means no error
    jobid: jobid,              // the generated job id
    description: "queued"      // indicates the SMS is queued for sending
  });
});

const PORT = 3000;
app.listen(PORT, () => {
  console.log(`Test API server is running on port ${PORT} with love`);
});
